# .github/workflows/cd.yaml

name: Deploy MLOps Model to GCE via SSH

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: project-cd53e609-dbd3-4daf-8e2
  ZONE: us-central1-a
  VM_NAME: application-server-20251206-155936
  REPO_DIR: mlops-model-production
  GCP_SA_EMAIL: github-actions-deployer@project-cd53e609-dbd3-4daf-8e2.iam.gserviceaccount.com
  WIF_PROVIDER_PATH: projects/55496059232/locations/global/workloadIdentityPools/github-pool/providers/github-provider

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Authenticate to GCP using Workload Identity Federation
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER_PATH }}
          service_account: ${{ env.GCP_SA_EMAIL }}
          
      - name: 3. Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
      
      - name: 4. Build Docker Images
        run: |
          # Construction du Backend
          docker build -t gcr.io/${{ env.PROJECT_ID }}/mlops-repo/backend:latest -f src/api/Dockerfile . 
          # Construction du Frontend (Ajouté)
          docker build -t gcr.io/${{ env.PROJECT_ID }}/mlops-repo/frontend:latest -f src/ui/Dockerfile .

      - name: 5. Push Docker Images to GAR
        run: |
          # Correction de l'hôte d'authentification Docker
          gcloud auth configure-docker us-central1-docker.pkg.dev # <-- L'hôte GAR
          
          # 2. Pousser les deux images avec le nouvel hôte
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/mlops-repo/backend:latest
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/mlops-repo/frontend:latest

      - name: 6. Deploy and Restart Containers on GCE
        run: |
          gcloud compute ssh eugeniebeauvillain@${{ env.VM_NAME }} \
            # ... autres options ...
            --command='
              # A. Authentification pour le pull des images (Hôte GAR)
              gcloud auth configure-docker us-central1-docker.pkg.dev # <-- L'hôte GAR
              
              # B. Pull les deux images (Hôte GAR)
              docker pull us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/mlops-repo/backend:latest
              docker pull us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/mlops-repo/frontend:latest
              
              # C. Redémarrer les services
              cd /home/eugeniebeauvillain/${{ env.REPO_DIR }} 
              docker compose up -d --force-recreate
            '